// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

 

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXt_6dvMw7591Jlslw-vN6XqTJRXPn2nY',
    appId: '1:546072807750:android:d2361a6ef112d36ef03d47',
    messagingSenderId: '546072807750',
    projectId: 'e-commerce-ef3c3',
    storageBucket: 'e-commerce-ef3c3.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjsbk3dwrcUk5CP79kAuiufZ-PDFLZDBA',
    appId: '1:546072807750:web:75663ba128916a13f03d47',
    messagingSenderId: '546072807750',
    projectId: 'e-commerce-ef3c3',
    authDomain: 'e-commerce-ef3c3.firebaseapp.com',
    storageBucket: 'e-commerce-ef3c3.firebasestorage.app',
    measurementId: 'G-PG3BKJZHT8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt4yBFR1k3YmTB78glHkeuKwzFzK-utfI',
    appId: '1:546072807750:ios:15e1e3acc406adbbf03d47',
    messagingSenderId: '546072807750',
    projectId: 'e-commerce-ef3c3',
    storageBucket: 'e-commerce-ef3c3.firebasestorage.app',
    iosClientId: '546072807750-7ggbi15nen57tvo1amd1giruhh3m4k3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceAdminApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt4yBFR1k3YmTB78glHkeuKwzFzK-utfI',
    appId: '1:546072807750:ios:15e1e3acc406adbbf03d47',
    messagingSenderId: '546072807750',
    projectId: 'e-commerce-ef3c3',
    storageBucket: 'e-commerce-ef3c3.firebasestorage.app',
    iosClientId: '546072807750-7ggbi15nen57tvo1amd1giruhh3m4k3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceAdminApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjsbk3dwrcUk5CP79kAuiufZ-PDFLZDBA',
    appId: '1:546072807750:web:089dc91b89983126f03d47',
    messagingSenderId: '546072807750',
    projectId: 'e-commerce-ef3c3',
    authDomain: 'e-commerce-ef3c3.firebaseapp.com',
    storageBucket: 'e-commerce-ef3c3.firebasestorage.app',
    measurementId: 'G-LZRBTYGFMS',
  );

}